// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SignupCreatedCode is the HTTP code returned for type SignupCreated
const SignupCreatedCode int = 201

/*
SignupCreated Client successfully created

swagger:response signupCreated
*/
type SignupCreated struct {
}

// NewSignupCreated creates SignupCreated with default headers values
func NewSignupCreated() *SignupCreated {

	return &SignupCreated{}
}

// WriteResponse to the client
func (o *SignupCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// SignupConflictCode is the HTTP code returned for type SignupConflict
const SignupConflictCode int = 409

/*
SignupConflict Client alredy exists

swagger:response signupConflict
*/
type SignupConflict struct {
}

// NewSignupConflict creates SignupConflict with default headers values
func NewSignupConflict() *SignupConflict {

	return &SignupConflict{}
}

// WriteResponse to the client
func (o *SignupConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// SignupUnprocessableEntityCode is the HTTP code returned for type SignupUnprocessableEntity
const SignupUnprocessableEntityCode int = 422

/*
SignupUnprocessableEntity Invalid params

swagger:response signupUnprocessableEntity
*/
type SignupUnprocessableEntity struct {
}

// NewSignupUnprocessableEntity creates SignupUnprocessableEntity with default headers values
func NewSignupUnprocessableEntity() *SignupUnprocessableEntity {

	return &SignupUnprocessableEntity{}
}

// WriteResponse to the client
func (o *SignupUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}

// SignupInternalServerErrorCode is the HTTP code returned for type SignupInternalServerError
const SignupInternalServerErrorCode int = 500

/*
SignupInternalServerError Internal error

swagger:response signupInternalServerError
*/
type SignupInternalServerError struct {
}

// NewSignupInternalServerError creates SignupInternalServerError with default headers values
func NewSignupInternalServerError() *SignupInternalServerError {

	return &SignupInternalServerError{}
}

// WriteResponse to the client
func (o *SignupInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
