// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"lim/internal/lim-handler/models"
)

// NewSignupParams creates a new SignupParams object
//
// There are no default values defined in the spec.
func NewSignupParams() SignupParams {

	return SignupParams{}
}

// SignupParams contains all the bound params for the signup operation
// typically these are obtained from a http.Request
//
// swagger:parameters signup
type SignupParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Информация о клиенте для регистрации
	  Required: true
	  In: body
	*/
	ClientInfo *models.ClientInfo
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSignupParams() beforehand.
func (o *SignupParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.ClientInfo
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("clientInfo", "body", ""))
			} else {
				res = append(res, errors.NewParseError("clientInfo", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.ClientInfo = &body
			}
		}
	} else {
		res = append(res, errors.Required("clientInfo", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
