// Code generated by go-swagger; DO NOT EDIT.

package halls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateHallHandlerFunc turns a function with the right signature into a create hall handler
type CreateHallHandlerFunc func(CreateHallParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateHallHandlerFunc) Handle(params CreateHallParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateHallHandler interface for that can handle valid create hall params
type CreateHallHandler interface {
	Handle(CreateHallParams, interface{}) middleware.Responder
}

// NewCreateHall creates a new http.Handler for the create hall operation
func NewCreateHall(ctx *middleware.Context, handler CreateHallHandler) *CreateHall {
	return &CreateHall{Context: ctx, Handler: handler}
}

/*
	CreateHall swagger:route POST /halls halls createHall

Create hall
*/
type CreateHall struct {
	Context *middleware.Context
	Handler CreateHallHandler
}

func (o *CreateHall) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateHallParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
