// Code generated by go-swagger; DO NOT EDIT.

package halls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateHallCreatedCode is the HTTP code returned for type CreateHallCreated
const CreateHallCreatedCode int = 201

/*
CreateHallCreated Hall successfully created

swagger:response createHallCreated
*/
type CreateHallCreated struct {
}

// NewCreateHallCreated creates CreateHallCreated with default headers values
func NewCreateHallCreated() *CreateHallCreated {

	return &CreateHallCreated{}
}

// WriteResponse to the client
func (o *CreateHallCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// CreateHallUnauthorizedCode is the HTTP code returned for type CreateHallUnauthorized
const CreateHallUnauthorizedCode int = 401

/*
CreateHallUnauthorized Authorization error

swagger:response createHallUnauthorized
*/
type CreateHallUnauthorized struct {
}

// NewCreateHallUnauthorized creates CreateHallUnauthorized with default headers values
func NewCreateHallUnauthorized() *CreateHallUnauthorized {

	return &CreateHallUnauthorized{}
}

// WriteResponse to the client
func (o *CreateHallUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// CreateHallForbiddenCode is the HTTP code returned for type CreateHallForbidden
const CreateHallForbiddenCode int = 403

/*
CreateHallForbidden No rights

swagger:response createHallForbidden
*/
type CreateHallForbidden struct {
}

// NewCreateHallForbidden creates CreateHallForbidden with default headers values
func NewCreateHallForbidden() *CreateHallForbidden {

	return &CreateHallForbidden{}
}

// WriteResponse to the client
func (o *CreateHallForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// CreateHallConflictCode is the HTTP code returned for type CreateHallConflict
const CreateHallConflictCode int = 409

/*
CreateHallConflict Hall alredy exists

swagger:response createHallConflict
*/
type CreateHallConflict struct {
}

// NewCreateHallConflict creates CreateHallConflict with default headers values
func NewCreateHallConflict() *CreateHallConflict {

	return &CreateHallConflict{}
}

// WriteResponse to the client
func (o *CreateHallConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// CreateHallInternalServerErrorCode is the HTTP code returned for type CreateHallInternalServerError
const CreateHallInternalServerErrorCode int = 500

/*
CreateHallInternalServerError Internal error

swagger:response createHallInternalServerError
*/
type CreateHallInternalServerError struct {
}

// NewCreateHallInternalServerError creates CreateHallInternalServerError with default headers values
func NewCreateHallInternalServerError() *CreateHallInternalServerError {

	return &CreateHallInternalServerError{}
}

// WriteResponse to the client
func (o *CreateHallInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
