// Code generated by go-swagger; DO NOT EDIT.

package halls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"lim/internal/lim-handler/models"
)

// GetHallsHandlerFunc turns a function with the right signature into a get halls handler
type GetHallsHandlerFunc func(GetHallsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetHallsHandlerFunc) Handle(params GetHallsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetHallsHandler interface for that can handle valid get halls params
type GetHallsHandler interface {
	Handle(GetHallsParams, interface{}) middleware.Responder
}

// NewGetHalls creates a new http.Handler for the get halls operation
func NewGetHalls(ctx *middleware.Context, handler GetHallsHandler) *GetHalls {
	return &GetHalls{Context: ctx, Handler: handler}
}

/*
	GetHalls swagger:route GET /halls/{date} halls getHalls

Get halls by date
*/
type GetHalls struct {
	Context *middleware.Context
	Handler GetHallsHandler
}

func (o *GetHalls) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetHallsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetHallsOKBodyItems0 get halls o k body items0
//
// swagger:model GetHallsOKBodyItems0
type GetHallsOKBodyItems0 struct {

	// hall
	Hall []*models.Hall `json:"hall"`

	// timestamp
	Timestamp string `json:"timestamp,omitempty"`
}

// Validate validates this get halls o k body items0
func (o *GetHallsOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateHall(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetHallsOKBodyItems0) validateHall(formats strfmt.Registry) error {
	if swag.IsZero(o.Hall) { // not required
		return nil
	}

	for i := 0; i < len(o.Hall); i++ {
		if swag.IsZero(o.Hall[i]) { // not required
			continue
		}

		if o.Hall[i] != nil {
			if err := o.Hall[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("hall" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("hall" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get halls o k body items0 based on the context it is used
func (o *GetHallsOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateHall(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetHallsOKBodyItems0) contextValidateHall(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Hall); i++ {

		if o.Hall[i] != nil {

			if swag.IsZero(o.Hall[i]) { // not required
				return nil
			}

			if err := o.Hall[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("hall" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("hall" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetHallsOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetHallsOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetHallsOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
