// Code generated by go-swagger; DO NOT EDIT.

package halls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetHallsOKCode is the HTTP code returned for type GetHallsOK
const GetHallsOKCode int = 200

/*
GetHallsOK Success

swagger:response getHallsOK
*/
type GetHallsOK struct {

	/*
	  In: Body
	*/
	Payload []*GetHallsOKBodyItems0 `json:"body,omitempty"`
}

// NewGetHallsOK creates GetHallsOK with default headers values
func NewGetHallsOK() *GetHallsOK {

	return &GetHallsOK{}
}

// WithPayload adds the payload to the get halls o k response
func (o *GetHallsOK) WithPayload(payload []*GetHallsOKBodyItems0) *GetHallsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get halls o k response
func (o *GetHallsOK) SetPayload(payload []*GetHallsOKBodyItems0) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHallsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*GetHallsOKBodyItems0, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetHallsUnauthorizedCode is the HTTP code returned for type GetHallsUnauthorized
const GetHallsUnauthorizedCode int = 401

/*
GetHallsUnauthorized Authorization error

swagger:response getHallsUnauthorized
*/
type GetHallsUnauthorized struct {
}

// NewGetHallsUnauthorized creates GetHallsUnauthorized with default headers values
func NewGetHallsUnauthorized() *GetHallsUnauthorized {

	return &GetHallsUnauthorized{}
}

// WriteResponse to the client
func (o *GetHallsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetHallsForbiddenCode is the HTTP code returned for type GetHallsForbidden
const GetHallsForbiddenCode int = 403

/*
GetHallsForbidden No rights

swagger:response getHallsForbidden
*/
type GetHallsForbidden struct {
}

// NewGetHallsForbidden creates GetHallsForbidden with default headers values
func NewGetHallsForbidden() *GetHallsForbidden {

	return &GetHallsForbidden{}
}

// WriteResponse to the client
func (o *GetHallsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetHallsUnprocessableEntityCode is the HTTP code returned for type GetHallsUnprocessableEntity
const GetHallsUnprocessableEntityCode int = 422

/*
GetHallsUnprocessableEntity Invalid params

swagger:response getHallsUnprocessableEntity
*/
type GetHallsUnprocessableEntity struct {
}

// NewGetHallsUnprocessableEntity creates GetHallsUnprocessableEntity with default headers values
func NewGetHallsUnprocessableEntity() *GetHallsUnprocessableEntity {

	return &GetHallsUnprocessableEntity{}
}

// WriteResponse to the client
func (o *GetHallsUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}

// GetHallsInternalServerErrorCode is the HTTP code returned for type GetHallsInternalServerError
const GetHallsInternalServerErrorCode int = 500

/*
GetHallsInternalServerError Internal error

swagger:response getHallsInternalServerError
*/
type GetHallsInternalServerError struct {
}

// NewGetHallsInternalServerError creates GetHallsInternalServerError with default headers values
func NewGetHallsInternalServerError() *GetHallsInternalServerError {

	return &GetHallsInternalServerError{}
}

// WriteResponse to the client
func (o *GetHallsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
