/* tslint:disable */
/* eslint-disable */
/**
 * Lost In Motion
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Client
 */
export interface Client {
    /**
     * 
     * @type {number}
     * @memberof Client
     */
    'client_id': number;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    'telephone': string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface ClientChangePassword
 */
export interface ClientChangePassword {
    /**
     * 
     * @type {string}
     * @memberof ClientChangePassword
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface ClientInfo
 */
export interface ClientInfo {
    /**
     * 
     * @type {string}
     * @memberof ClientInfo
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ClientInfo
     */
    'telephone': string;
    /**
     * 
     * @type {string}
     * @memberof ClientInfo
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof ClientInfo
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface ClientLoginInfo
 */
export interface ClientLoginInfo {
    /**
     * 
     * @type {string}
     * @memberof ClientLoginInfo
     */
    'telephone': string;
    /**
     * 
     * @type {string}
     * @memberof ClientLoginInfo
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface Coach
 */
export interface Coach {
    /**
     * 
     * @type {number}
     * @memberof Coach
     */
    'coach_id': number;
    /**
     * 
     * @type {string}
     * @memberof Coach
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface CoachInfo
 */
export interface CoachInfo {
    /**
     * 
     * @type {string}
     * @memberof CoachInfo
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface GetHalls200ResponseInner
 */
export interface GetHalls200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof GetHalls200ResponseInner
     */
    'timestamp'?: string;
    /**
     * 
     * @type {Array<Hall>}
     * @memberof GetHalls200ResponseInner
     */
    'hall'?: Array<Hall>;
}
/**
 * 
 * @export
 * @interface Hall
 */
export interface Hall {
    /**
     * 
     * @type {number}
     * @memberof Hall
     */
    'hall_id': number;
    /**
     * 
     * @type {number}
     * @memberof Hall
     */
    'number': number;
}
/**
 * 
 * @export
 * @interface HallInfo
 */
export interface HallInfo {
    /**
     * 
     * @type {number}
     * @memberof HallInfo
     */
    'number': number;
}
/**
 * 
 * @export
 * @interface Token
 */
export interface Token {
    /**
     * JWT access key
     * @type {string}
     * @memberof Token
     */
    'access_key'?: string;
}
/**
 * 
 * @export
 * @interface Training
 */
export interface Training {
    /**
     * 
     * @type {number}
     * @memberof Training
     */
    'training_id': number;
    /**
     * 
     * @type {string}
     * @memberof Training
     */
    'coach_name': string;
    /**
     * 
     * @type {number}
     * @memberof Training
     */
    'hall_number': number;
    /**
     * 
     * @type {string}
     * @memberof Training
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Training
     */
    'date_time': string;
    /**
     * 
     * @type {number}
     * @memberof Training
     */
    'places_num': number;
}
/**
 * 
 * @export
 * @interface TrainingID
 */
export interface TrainingID {
    /**
     * 
     * @type {number}
     * @memberof TrainingID
     */
    'training_id': number;
}
/**
 * 
 * @export
 * @interface TrainingInfo
 */
export interface TrainingInfo {
    /**
     * 
     * @type {string}
     * @memberof TrainingInfo
     */
    'coach_name': string;
    /**
     * 
     * @type {number}
     * @memberof TrainingInfo
     */
    'hall_number': number;
    /**
     * 
     * @type {string}
     * @memberof TrainingInfo
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof TrainingInfo
     */
    'date_time': string;
    /**
     * 
     * @type {number}
     * @memberof TrainingInfo
     */
    'places_num': number;
}

/**
 * AssignmentsApi - axios parameter creator
 * @export
 */
export const AssignmentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create assignment
         * @param {TrainingID} trainingId Идентификатор тренировки
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAssignment: async (trainingId: TrainingID, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'trainingId' is not null or undefined
            assertParamExists('createAssignment', 'trainingId', trainingId)
            const localVarPath = `/assignments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTAuth required
            await setApiKeyToObject(localVarHeaderParameter, "token", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(trainingId, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete assignment
         * @param {TrainingID} trainingId Идентификатор тренировки
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAssignment: async (trainingId: TrainingID, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'trainingId' is not null or undefined
            assertParamExists('deleteAssignment', 'trainingId', trainingId)
            const localVarPath = `/assignments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTAuth required
            await setApiKeyToObject(localVarHeaderParameter, "token", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(trainingId, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AssignmentsApi - functional programming interface
 * @export
 */
export const AssignmentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AssignmentsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create assignment
         * @param {TrainingID} trainingId Идентификатор тренировки
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAssignment(trainingId: TrainingID, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAssignment(trainingId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AssignmentsApi.createAssignment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete assignment
         * @param {TrainingID} trainingId Идентификатор тренировки
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteAssignment(trainingId: TrainingID, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteAssignment(trainingId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AssignmentsApi.deleteAssignment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AssignmentsApi - factory interface
 * @export
 */
export const AssignmentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AssignmentsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create assignment
         * @param {TrainingID} trainingId Идентификатор тренировки
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAssignment(trainingId: TrainingID, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createAssignment(trainingId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete assignment
         * @param {TrainingID} trainingId Идентификатор тренировки
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAssignment(trainingId: TrainingID, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteAssignment(trainingId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AssignmentsApi - object-oriented interface
 * @export
 * @class AssignmentsApi
 * @extends {BaseAPI}
 */
export class AssignmentsApi extends BaseAPI {
    /**
     * 
     * @summary Create assignment
     * @param {TrainingID} trainingId Идентификатор тренировки
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssignmentsApi
     */
    public createAssignment(trainingId: TrainingID, options?: RawAxiosRequestConfig) {
        return AssignmentsApiFp(this.configuration).createAssignment(trainingId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete assignment
     * @param {TrainingID} trainingId Идентификатор тренировки
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssignmentsApi
     */
    public deleteAssignment(trainingId: TrainingID, options?: RawAxiosRequestConfig) {
        return AssignmentsApiFp(this.configuration).deleteAssignment(trainingId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Login
         * @param {ClientLoginInfo} clientLoginInfo Информация о клиенте для входа
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (clientLoginInfo: ClientLoginInfo, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientLoginInfo' is not null or undefined
            assertParamExists('login', 'clientLoginInfo', clientLoginInfo)
            const localVarPath = `/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(clientLoginInfo, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create client
         * @param {ClientInfo} clientInfo Информация о клиенте для регистрации
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signup: async (clientInfo: ClientInfo, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientInfo' is not null or undefined
            assertParamExists('signup', 'clientInfo', clientInfo)
            const localVarPath = `/signup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(clientInfo, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Login
         * @param {ClientLoginInfo} clientLoginInfo Информация о клиенте для входа
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(clientLoginInfo: ClientLoginInfo, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Token>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(clientLoginInfo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create client
         * @param {ClientInfo} clientInfo Информация о клиенте для регистрации
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signup(clientInfo: ClientInfo, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signup(clientInfo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.signup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @summary Login
         * @param {ClientLoginInfo} clientLoginInfo Информация о клиенте для входа
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(clientLoginInfo: ClientLoginInfo, options?: RawAxiosRequestConfig): AxiosPromise<Token> {
            return localVarFp.login(clientLoginInfo, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create client
         * @param {ClientInfo} clientInfo Информация о клиенте для регистрации
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signup(clientInfo: ClientInfo, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.signup(clientInfo, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @summary Login
     * @param {ClientLoginInfo} clientLoginInfo Информация о клиенте для входа
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public login(clientLoginInfo: ClientLoginInfo, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).login(clientLoginInfo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create client
     * @param {ClientInfo} clientInfo Информация о клиенте для регистрации
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public signup(clientInfo: ClientInfo, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).signup(clientInfo, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ClientsApi - axios parameter creator
 * @export
 */
export const ClientsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Change password
         * @param {ClientChangePassword} newPassword Новый пароль
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword: async (newPassword: ClientChangePassword, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'newPassword' is not null or undefined
            assertParamExists('changePassword', 'newPassword', newPassword)
            const localVarPath = `/clients`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTAuth required
            await setApiKeyToObject(localVarHeaderParameter, "token", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(newPassword, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get trainings by client
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTrainingsByClient: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/clients/trainings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTAuth required
            await setApiKeyToObject(localVarHeaderParameter, "token", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ClientsApi - functional programming interface
 * @export
 */
export const ClientsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ClientsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Change password
         * @param {ClientChangePassword} newPassword Новый пароль
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changePassword(newPassword: ClientChangePassword, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changePassword(newPassword, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClientsApi.changePassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get trainings by client
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTrainingsByClient(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Training>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTrainingsByClient(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClientsApi.getTrainingsByClient']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ClientsApi - factory interface
 * @export
 */
export const ClientsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ClientsApiFp(configuration)
    return {
        /**
         * 
         * @summary Change password
         * @param {ClientChangePassword} newPassword Новый пароль
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword(newPassword: ClientChangePassword, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.changePassword(newPassword, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get trainings by client
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTrainingsByClient(options?: RawAxiosRequestConfig): AxiosPromise<Array<Training>> {
            return localVarFp.getTrainingsByClient(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ClientsApi - object-oriented interface
 * @export
 * @class ClientsApi
 * @extends {BaseAPI}
 */
export class ClientsApi extends BaseAPI {
    /**
     * 
     * @summary Change password
     * @param {ClientChangePassword} newPassword Новый пароль
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClientsApi
     */
    public changePassword(newPassword: ClientChangePassword, options?: RawAxiosRequestConfig) {
        return ClientsApiFp(this.configuration).changePassword(newPassword, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get trainings by client
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClientsApi
     */
    public getTrainingsByClient(options?: RawAxiosRequestConfig) {
        return ClientsApiFp(this.configuration).getTrainingsByClient(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CoachesApi - axios parameter creator
 * @export
 */
export const CoachesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create coach
         * @param {CoachInfo} coachInfo Информация о тренере для создания
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCoach: async (coachInfo: CoachInfo, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'coachInfo' is not null or undefined
            assertParamExists('createCoach', 'coachInfo', coachInfo)
            const localVarPath = `/coaches`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTAuth required
            await setApiKeyToObject(localVarHeaderParameter, "token", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(coachInfo, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get coaches
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCoaches: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/coaches`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTAuth required
            await setApiKeyToObject(localVarHeaderParameter, "token", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CoachesApi - functional programming interface
 * @export
 */
export const CoachesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CoachesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create coach
         * @param {CoachInfo} coachInfo Информация о тренере для создания
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCoach(coachInfo: CoachInfo, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCoach(coachInfo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoachesApi.createCoach']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get coaches
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCoaches(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Coach>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCoaches(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoachesApi.getCoaches']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CoachesApi - factory interface
 * @export
 */
export const CoachesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CoachesApiFp(configuration)
    return {
        /**
         * 
         * @summary Create coach
         * @param {CoachInfo} coachInfo Информация о тренере для создания
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCoach(coachInfo: CoachInfo, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createCoach(coachInfo, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get coaches
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCoaches(options?: RawAxiosRequestConfig): AxiosPromise<Array<Coach>> {
            return localVarFp.getCoaches(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CoachesApi - object-oriented interface
 * @export
 * @class CoachesApi
 * @extends {BaseAPI}
 */
export class CoachesApi extends BaseAPI {
    /**
     * 
     * @summary Create coach
     * @param {CoachInfo} coachInfo Информация о тренере для создания
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoachesApi
     */
    public createCoach(coachInfo: CoachInfo, options?: RawAxiosRequestConfig) {
        return CoachesApiFp(this.configuration).createCoach(coachInfo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get coaches
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoachesApi
     */
    public getCoaches(options?: RawAxiosRequestConfig) {
        return CoachesApiFp(this.configuration).getCoaches(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * HallsApi - axios parameter creator
 * @export
 */
export const HallsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create hall
         * @param {HallInfo} hallInfo Информация о зале для создания
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createHall: async (hallInfo: HallInfo, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'hallInfo' is not null or undefined
            assertParamExists('createHall', 'hallInfo', hallInfo)
            const localVarPath = `/halls`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTAuth required
            await setApiKeyToObject(localVarHeaderParameter, "token", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(hallInfo, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get halls by date
         * @param {string} date Дата
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHalls: async (date: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'date' is not null or undefined
            assertParamExists('getHalls', 'date', date)
            const localVarPath = `/halls/{date}`
                .replace(`{${"date"}}`, encodeURIComponent(String(date)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTAuth required
            await setApiKeyToObject(localVarHeaderParameter, "token", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HallsApi - functional programming interface
 * @export
 */
export const HallsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HallsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create hall
         * @param {HallInfo} hallInfo Информация о зале для создания
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createHall(hallInfo: HallInfo, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createHall(hallInfo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HallsApi.createHall']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get halls by date
         * @param {string} date Дата
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHalls(date: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetHalls200ResponseInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHalls(date, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HallsApi.getHalls']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HallsApi - factory interface
 * @export
 */
export const HallsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HallsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create hall
         * @param {HallInfo} hallInfo Информация о зале для создания
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createHall(hallInfo: HallInfo, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createHall(hallInfo, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get halls by date
         * @param {string} date Дата
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHalls(date: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GetHalls200ResponseInner>> {
            return localVarFp.getHalls(date, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HallsApi - object-oriented interface
 * @export
 * @class HallsApi
 * @extends {BaseAPI}
 */
export class HallsApi extends BaseAPI {
    /**
     * 
     * @summary Create hall
     * @param {HallInfo} hallInfo Информация о зале для создания
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HallsApi
     */
    public createHall(hallInfo: HallInfo, options?: RawAxiosRequestConfig) {
        return HallsApiFp(this.configuration).createHall(hallInfo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get halls by date
     * @param {string} date Дата
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HallsApi
     */
    public getHalls(date: string, options?: RawAxiosRequestConfig) {
        return HallsApiFp(this.configuration).getHalls(date, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ScheduleApi - axios parameter creator
 * @export
 */
export const ScheduleApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get training schedule
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSchedule: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/schedule`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ScheduleApi - functional programming interface
 * @export
 */
export const ScheduleApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ScheduleApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get training schedule
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSchedule(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Training>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSchedule(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ScheduleApi.getSchedule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ScheduleApi - factory interface
 * @export
 */
export const ScheduleApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ScheduleApiFp(configuration)
    return {
        /**
         * 
         * @summary Get training schedule
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSchedule(options?: RawAxiosRequestConfig): AxiosPromise<Array<Training>> {
            return localVarFp.getSchedule(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ScheduleApi - object-oriented interface
 * @export
 * @class ScheduleApi
 * @extends {BaseAPI}
 */
export class ScheduleApi extends BaseAPI {
    /**
     * 
     * @summary Get training schedule
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScheduleApi
     */
    public getSchedule(options?: RawAxiosRequestConfig) {
        return ScheduleApiFp(this.configuration).getSchedule(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TrainingsApi - axios parameter creator
 * @export
 */
export const TrainingsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create training
         * @param {TrainingInfo} trainingInfo Информация о тренировке для создания
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTraining: async (trainingInfo: TrainingInfo, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'trainingInfo' is not null or undefined
            assertParamExists('createTraining', 'trainingInfo', trainingInfo)
            const localVarPath = `/trainings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTAuth required
            await setApiKeyToObject(localVarHeaderParameter, "token", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(trainingInfo, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete training
         * @param {TrainingID} trainingId Идентификатор тренировки
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTraining: async (trainingId: TrainingID, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'trainingId' is not null or undefined
            assertParamExists('deleteTraining', 'trainingId', trainingId)
            const localVarPath = `/trainings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTAuth required
            await setApiKeyToObject(localVarHeaderParameter, "token", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(trainingId, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TrainingsApi - functional programming interface
 * @export
 */
export const TrainingsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TrainingsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create training
         * @param {TrainingInfo} trainingInfo Информация о тренировке для создания
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTraining(trainingInfo: TrainingInfo, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTraining(trainingInfo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TrainingsApi.createTraining']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete training
         * @param {TrainingID} trainingId Идентификатор тренировки
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTraining(trainingId: TrainingID, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTraining(trainingId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TrainingsApi.deleteTraining']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TrainingsApi - factory interface
 * @export
 */
export const TrainingsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TrainingsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create training
         * @param {TrainingInfo} trainingInfo Информация о тренировке для создания
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTraining(trainingInfo: TrainingInfo, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createTraining(trainingInfo, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete training
         * @param {TrainingID} trainingId Идентификатор тренировки
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTraining(trainingId: TrainingID, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteTraining(trainingId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TrainingsApi - object-oriented interface
 * @export
 * @class TrainingsApi
 * @extends {BaseAPI}
 */
export class TrainingsApi extends BaseAPI {
    /**
     * 
     * @summary Create training
     * @param {TrainingInfo} trainingInfo Информация о тренировке для создания
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrainingsApi
     */
    public createTraining(trainingInfo: TrainingInfo, options?: RawAxiosRequestConfig) {
        return TrainingsApiFp(this.configuration).createTraining(trainingInfo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete training
     * @param {TrainingID} trainingId Идентификатор тренировки
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrainingsApi
     */
    public deleteTraining(trainingId: TrainingID, options?: RawAxiosRequestConfig) {
        return TrainingsApiFp(this.configuration).deleteTraining(trainingId, options).then((request) => request(this.axios, this.basePath));
    }
}



