// Code generated by go-swagger; DO NOT EDIT.

package assignments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateAssignmentCreatedCode is the HTTP code returned for type CreateAssignmentCreated
const CreateAssignmentCreatedCode int = 201

/*
CreateAssignmentCreated Assignment successfully created

swagger:response createAssignmentCreated
*/
type CreateAssignmentCreated struct {
}

// NewCreateAssignmentCreated creates CreateAssignmentCreated with default headers values
func NewCreateAssignmentCreated() *CreateAssignmentCreated {

	return &CreateAssignmentCreated{}
}

// WriteResponse to the client
func (o *CreateAssignmentCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// CreateAssignmentUnauthorizedCode is the HTTP code returned for type CreateAssignmentUnauthorized
const CreateAssignmentUnauthorizedCode int = 401

/*
CreateAssignmentUnauthorized Authorization error

swagger:response createAssignmentUnauthorized
*/
type CreateAssignmentUnauthorized struct {
}

// NewCreateAssignmentUnauthorized creates CreateAssignmentUnauthorized with default headers values
func NewCreateAssignmentUnauthorized() *CreateAssignmentUnauthorized {

	return &CreateAssignmentUnauthorized{}
}

// WriteResponse to the client
func (o *CreateAssignmentUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// CreateAssignmentForbiddenCode is the HTTP code returned for type CreateAssignmentForbidden
const CreateAssignmentForbiddenCode int = 403

/*
CreateAssignmentForbidden No rights

swagger:response createAssignmentForbidden
*/
type CreateAssignmentForbidden struct {
}

// NewCreateAssignmentForbidden creates CreateAssignmentForbidden with default headers values
func NewCreateAssignmentForbidden() *CreateAssignmentForbidden {

	return &CreateAssignmentForbidden{}
}

// WriteResponse to the client
func (o *CreateAssignmentForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// CreateAssignmentNotFoundCode is the HTTP code returned for type CreateAssignmentNotFound
const CreateAssignmentNotFoundCode int = 404

/*
CreateAssignmentNotFound Not found

swagger:response createAssignmentNotFound
*/
type CreateAssignmentNotFound struct {
}

// NewCreateAssignmentNotFound creates CreateAssignmentNotFound with default headers values
func NewCreateAssignmentNotFound() *CreateAssignmentNotFound {

	return &CreateAssignmentNotFound{}
}

// WriteResponse to the client
func (o *CreateAssignmentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// CreateAssignmentConflictCode is the HTTP code returned for type CreateAssignmentConflict
const CreateAssignmentConflictCode int = 409

/*
CreateAssignmentConflict Validation error

swagger:response createAssignmentConflict
*/
type CreateAssignmentConflict struct {
}

// NewCreateAssignmentConflict creates CreateAssignmentConflict with default headers values
func NewCreateAssignmentConflict() *CreateAssignmentConflict {

	return &CreateAssignmentConflict{}
}

// WriteResponse to the client
func (o *CreateAssignmentConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// CreateAssignmentUnprocessableEntityCode is the HTTP code returned for type CreateAssignmentUnprocessableEntity
const CreateAssignmentUnprocessableEntityCode int = 422

/*
CreateAssignmentUnprocessableEntity Invalid params

swagger:response createAssignmentUnprocessableEntity
*/
type CreateAssignmentUnprocessableEntity struct {
}

// NewCreateAssignmentUnprocessableEntity creates CreateAssignmentUnprocessableEntity with default headers values
func NewCreateAssignmentUnprocessableEntity() *CreateAssignmentUnprocessableEntity {

	return &CreateAssignmentUnprocessableEntity{}
}

// WriteResponse to the client
func (o *CreateAssignmentUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}

// CreateAssignmentInternalServerErrorCode is the HTTP code returned for type CreateAssignmentInternalServerError
const CreateAssignmentInternalServerErrorCode int = 500

/*
CreateAssignmentInternalServerError Internal error

swagger:response createAssignmentInternalServerError
*/
type CreateAssignmentInternalServerError struct {
}

// NewCreateAssignmentInternalServerError creates CreateAssignmentInternalServerError with default headers values
func NewCreateAssignmentInternalServerError() *CreateAssignmentInternalServerError {

	return &CreateAssignmentInternalServerError{}
}

// WriteResponse to the client
func (o *CreateAssignmentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
