// Code generated by go-swagger; DO NOT EDIT.

package assignments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteAssignmentHandlerFunc turns a function with the right signature into a delete assignment handler
type DeleteAssignmentHandlerFunc func(DeleteAssignmentParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteAssignmentHandlerFunc) Handle(params DeleteAssignmentParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteAssignmentHandler interface for that can handle valid delete assignment params
type DeleteAssignmentHandler interface {
	Handle(DeleteAssignmentParams, interface{}) middleware.Responder
}

// NewDeleteAssignment creates a new http.Handler for the delete assignment operation
func NewDeleteAssignment(ctx *middleware.Context, handler DeleteAssignmentHandler) *DeleteAssignment {
	return &DeleteAssignment{Context: ctx, Handler: handler}
}

/*
	DeleteAssignment swagger:route DELETE /assignments assignments deleteAssignment

Delete assignment
*/
type DeleteAssignment struct {
	Context *middleware.Context
	Handler DeleteAssignmentHandler
}

func (o *DeleteAssignment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteAssignmentParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
