// Code generated by go-swagger; DO NOT EDIT.

package assignments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteAssignmentOKCode is the HTTP code returned for type DeleteAssignmentOK
const DeleteAssignmentOKCode int = 200

/*
DeleteAssignmentOK Assignment successfully deleted

swagger:response deleteAssignmentOK
*/
type DeleteAssignmentOK struct {
}

// NewDeleteAssignmentOK creates DeleteAssignmentOK with default headers values
func NewDeleteAssignmentOK() *DeleteAssignmentOK {

	return &DeleteAssignmentOK{}
}

// WriteResponse to the client
func (o *DeleteAssignmentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteAssignmentUnauthorizedCode is the HTTP code returned for type DeleteAssignmentUnauthorized
const DeleteAssignmentUnauthorizedCode int = 401

/*
DeleteAssignmentUnauthorized Authorization error

swagger:response deleteAssignmentUnauthorized
*/
type DeleteAssignmentUnauthorized struct {
}

// NewDeleteAssignmentUnauthorized creates DeleteAssignmentUnauthorized with default headers values
func NewDeleteAssignmentUnauthorized() *DeleteAssignmentUnauthorized {

	return &DeleteAssignmentUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteAssignmentUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DeleteAssignmentForbiddenCode is the HTTP code returned for type DeleteAssignmentForbidden
const DeleteAssignmentForbiddenCode int = 403

/*
DeleteAssignmentForbidden No rights

swagger:response deleteAssignmentForbidden
*/
type DeleteAssignmentForbidden struct {
}

// NewDeleteAssignmentForbidden creates DeleteAssignmentForbidden with default headers values
func NewDeleteAssignmentForbidden() *DeleteAssignmentForbidden {

	return &DeleteAssignmentForbidden{}
}

// WriteResponse to the client
func (o *DeleteAssignmentForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// DeleteAssignmentNotFoundCode is the HTTP code returned for type DeleteAssignmentNotFound
const DeleteAssignmentNotFoundCode int = 404

/*
DeleteAssignmentNotFound Not found

swagger:response deleteAssignmentNotFound
*/
type DeleteAssignmentNotFound struct {
}

// NewDeleteAssignmentNotFound creates DeleteAssignmentNotFound with default headers values
func NewDeleteAssignmentNotFound() *DeleteAssignmentNotFound {

	return &DeleteAssignmentNotFound{}
}

// WriteResponse to the client
func (o *DeleteAssignmentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteAssignmentUnprocessableEntityCode is the HTTP code returned for type DeleteAssignmentUnprocessableEntity
const DeleteAssignmentUnprocessableEntityCode int = 422

/*
DeleteAssignmentUnprocessableEntity Invalid params

swagger:response deleteAssignmentUnprocessableEntity
*/
type DeleteAssignmentUnprocessableEntity struct {
}

// NewDeleteAssignmentUnprocessableEntity creates DeleteAssignmentUnprocessableEntity with default headers values
func NewDeleteAssignmentUnprocessableEntity() *DeleteAssignmentUnprocessableEntity {

	return &DeleteAssignmentUnprocessableEntity{}
}

// WriteResponse to the client
func (o *DeleteAssignmentUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}

// DeleteAssignmentInternalServerErrorCode is the HTTP code returned for type DeleteAssignmentInternalServerError
const DeleteAssignmentInternalServerErrorCode int = 500

/*
DeleteAssignmentInternalServerError Internal error

swagger:response deleteAssignmentInternalServerError
*/
type DeleteAssignmentInternalServerError struct {
}

// NewDeleteAssignmentInternalServerError creates DeleteAssignmentInternalServerError with default headers values
func NewDeleteAssignmentInternalServerError() *DeleteAssignmentInternalServerError {

	return &DeleteAssignmentInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteAssignmentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
