// Code generated by go-swagger; DO NOT EDIT.

package coaches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateCoachHandlerFunc turns a function with the right signature into a create coach handler
type CreateCoachHandlerFunc func(CreateCoachParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateCoachHandlerFunc) Handle(params CreateCoachParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateCoachHandler interface for that can handle valid create coach params
type CreateCoachHandler interface {
	Handle(CreateCoachParams, interface{}) middleware.Responder
}

// NewCreateCoach creates a new http.Handler for the create coach operation
func NewCreateCoach(ctx *middleware.Context, handler CreateCoachHandler) *CreateCoach {
	return &CreateCoach{Context: ctx, Handler: handler}
}

/*
	CreateCoach swagger:route POST /coaches coaches createCoach

Create coach
*/
type CreateCoach struct {
	Context *middleware.Context
	Handler CreateCoachHandler
}

func (o *CreateCoach) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateCoachParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
