// Code generated by go-swagger; DO NOT EDIT.

package coaches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateCoachCreatedCode is the HTTP code returned for type CreateCoachCreated
const CreateCoachCreatedCode int = 201

/*
CreateCoachCreated Coach successfully created

swagger:response createCoachCreated
*/
type CreateCoachCreated struct {
}

// NewCreateCoachCreated creates CreateCoachCreated with default headers values
func NewCreateCoachCreated() *CreateCoachCreated {

	return &CreateCoachCreated{}
}

// WriteResponse to the client
func (o *CreateCoachCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// CreateCoachUnauthorizedCode is the HTTP code returned for type CreateCoachUnauthorized
const CreateCoachUnauthorizedCode int = 401

/*
CreateCoachUnauthorized Authorization error

swagger:response createCoachUnauthorized
*/
type CreateCoachUnauthorized struct {
}

// NewCreateCoachUnauthorized creates CreateCoachUnauthorized with default headers values
func NewCreateCoachUnauthorized() *CreateCoachUnauthorized {

	return &CreateCoachUnauthorized{}
}

// WriteResponse to the client
func (o *CreateCoachUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// CreateCoachForbiddenCode is the HTTP code returned for type CreateCoachForbidden
const CreateCoachForbiddenCode int = 403

/*
CreateCoachForbidden No rights

swagger:response createCoachForbidden
*/
type CreateCoachForbidden struct {
}

// NewCreateCoachForbidden creates CreateCoachForbidden with default headers values
func NewCreateCoachForbidden() *CreateCoachForbidden {

	return &CreateCoachForbidden{}
}

// WriteResponse to the client
func (o *CreateCoachForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// CreateCoachConflictCode is the HTTP code returned for type CreateCoachConflict
const CreateCoachConflictCode int = 409

/*
CreateCoachConflict Coach alredy exists

swagger:response createCoachConflict
*/
type CreateCoachConflict struct {
}

// NewCreateCoachConflict creates CreateCoachConflict with default headers values
func NewCreateCoachConflict() *CreateCoachConflict {

	return &CreateCoachConflict{}
}

// WriteResponse to the client
func (o *CreateCoachConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// CreateCoachInternalServerErrorCode is the HTTP code returned for type CreateCoachInternalServerError
const CreateCoachInternalServerErrorCode int = 500

/*
CreateCoachInternalServerError Internal error

swagger:response createCoachInternalServerError
*/
type CreateCoachInternalServerError struct {
}

// NewCreateCoachInternalServerError creates CreateCoachInternalServerError with default headers values
func NewCreateCoachInternalServerError() *CreateCoachInternalServerError {

	return &CreateCoachInternalServerError{}
}

// WriteResponse to the client
func (o *CreateCoachInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
