// Code generated by go-swagger; DO NOT EDIT.

package coaches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"lim/internal/lim-handler/models"
)

// GetCoachesOKCode is the HTTP code returned for type GetCoachesOK
const GetCoachesOKCode int = 200

/*
GetCoachesOK Success

swagger:response getCoachesOK
*/
type GetCoachesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Coach `json:"body,omitempty"`
}

// NewGetCoachesOK creates GetCoachesOK with default headers values
func NewGetCoachesOK() *GetCoachesOK {

	return &GetCoachesOK{}
}

// WithPayload adds the payload to the get coaches o k response
func (o *GetCoachesOK) WithPayload(payload []*models.Coach) *GetCoachesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get coaches o k response
func (o *GetCoachesOK) SetPayload(payload []*models.Coach) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCoachesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Coach, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetCoachesUnauthorizedCode is the HTTP code returned for type GetCoachesUnauthorized
const GetCoachesUnauthorizedCode int = 401

/*
GetCoachesUnauthorized Authorization error

swagger:response getCoachesUnauthorized
*/
type GetCoachesUnauthorized struct {
}

// NewGetCoachesUnauthorized creates GetCoachesUnauthorized with default headers values
func NewGetCoachesUnauthorized() *GetCoachesUnauthorized {

	return &GetCoachesUnauthorized{}
}

// WriteResponse to the client
func (o *GetCoachesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetCoachesForbiddenCode is the HTTP code returned for type GetCoachesForbidden
const GetCoachesForbiddenCode int = 403

/*
GetCoachesForbidden No rights

swagger:response getCoachesForbidden
*/
type GetCoachesForbidden struct {
}

// NewGetCoachesForbidden creates GetCoachesForbidden with default headers values
func NewGetCoachesForbidden() *GetCoachesForbidden {

	return &GetCoachesForbidden{}
}

// WriteResponse to the client
func (o *GetCoachesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetCoachesInternalServerErrorCode is the HTTP code returned for type GetCoachesInternalServerError
const GetCoachesInternalServerErrorCode int = 500

/*
GetCoachesInternalServerError Internal error

swagger:response getCoachesInternalServerError
*/
type GetCoachesInternalServerError struct {
}

// NewGetCoachesInternalServerError creates GetCoachesInternalServerError with default headers values
func NewGetCoachesInternalServerError() *GetCoachesInternalServerError {

	return &GetCoachesInternalServerError{}
}

// WriteResponse to the client
func (o *GetCoachesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
