// Code generated by go-swagger; DO NOT EDIT.

package coaches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCoachesHandlerFunc turns a function with the right signature into a get coaches handler
type GetCoachesHandlerFunc func(GetCoachesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCoachesHandlerFunc) Handle(params GetCoachesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetCoachesHandler interface for that can handle valid get coaches params
type GetCoachesHandler interface {
	Handle(GetCoachesParams, interface{}) middleware.Responder
}

// NewGetCoaches creates a new http.Handler for the get coaches operation
func NewGetCoaches(ctx *middleware.Context, handler GetCoachesHandler) *GetCoaches {
	return &GetCoaches{Context: ctx, Handler: handler}
}

/*
	GetCoaches swagger:route GET /coaches coaches getCoaches

Get coaches
*/
type GetCoaches struct {
	Context *middleware.Context
	Handler GetCoachesHandler
}

func (o *GetCoaches) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCoachesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
