// Code generated by MockGen. DO NOT EDIT.
// Source: coach.go

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "lim/internal/lim-core/models"
)

// MockCoachRepository is a mock of CoachRepository interface.
type MockCoachRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCoachRepositoryMockRecorder
}

// MockCoachRepositoryMockRecorder is the mock recorder for MockCoachRepository.
type MockCoachRepositoryMockRecorder struct {
	mock *MockCoachRepository
}

// NewMockCoachRepository creates a new mock instance.
func NewMockCoachRepository(ctrl *gomock.Controller) *MockCoachRepository {
	mock := &MockCoachRepository{ctrl: ctrl}
	mock.recorder = &MockCoachRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoachRepository) EXPECT() *MockCoachRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCoachRepository) Create(ctx context.Context, coach *models.Coach) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, coach)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCoachRepositoryMockRecorder) Create(ctx, coach interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCoachRepository)(nil).Create), ctx, coach)
}

// GetAll mocks base method.
func (m *MockCoachRepository) GetAll(ctx context.Context) ([]models.Coach, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]models.Coach)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCoachRepositoryMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCoachRepository)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockCoachRepository) GetByID(ctx context.Context, id uint64) (*models.Coach, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Coach)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCoachRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCoachRepository)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockCoachRepository) GetByName(ctx context.Context, name string) (*models.Coach, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*models.Coach)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockCoachRepositoryMockRecorder) GetByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockCoachRepository)(nil).GetByName), ctx, name)
}
