// Code generated by go-swagger; DO NOT EDIT.

package clients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ChangePasswordOKCode is the HTTP code returned for type ChangePasswordOK
const ChangePasswordOKCode int = 200

/*
ChangePasswordOK Success

swagger:response changePasswordOK
*/
type ChangePasswordOK struct {
}

// NewChangePasswordOK creates ChangePasswordOK with default headers values
func NewChangePasswordOK() *ChangePasswordOK {

	return &ChangePasswordOK{}
}

// WriteResponse to the client
func (o *ChangePasswordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// ChangePasswordUnauthorizedCode is the HTTP code returned for type ChangePasswordUnauthorized
const ChangePasswordUnauthorizedCode int = 401

/*
ChangePasswordUnauthorized Authorization error

swagger:response changePasswordUnauthorized
*/
type ChangePasswordUnauthorized struct {
}

// NewChangePasswordUnauthorized creates ChangePasswordUnauthorized with default headers values
func NewChangePasswordUnauthorized() *ChangePasswordUnauthorized {

	return &ChangePasswordUnauthorized{}
}

// WriteResponse to the client
func (o *ChangePasswordUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// ChangePasswordForbiddenCode is the HTTP code returned for type ChangePasswordForbidden
const ChangePasswordForbiddenCode int = 403

/*
ChangePasswordForbidden No rights

swagger:response changePasswordForbidden
*/
type ChangePasswordForbidden struct {
}

// NewChangePasswordForbidden creates ChangePasswordForbidden with default headers values
func NewChangePasswordForbidden() *ChangePasswordForbidden {

	return &ChangePasswordForbidden{}
}

// WriteResponse to the client
func (o *ChangePasswordForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// ChangePasswordNotFoundCode is the HTTP code returned for type ChangePasswordNotFound
const ChangePasswordNotFoundCode int = 404

/*
ChangePasswordNotFound No such client

swagger:response changePasswordNotFound
*/
type ChangePasswordNotFound struct {
}

// NewChangePasswordNotFound creates ChangePasswordNotFound with default headers values
func NewChangePasswordNotFound() *ChangePasswordNotFound {

	return &ChangePasswordNotFound{}
}

// WriteResponse to the client
func (o *ChangePasswordNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// ChangePasswordInternalServerErrorCode is the HTTP code returned for type ChangePasswordInternalServerError
const ChangePasswordInternalServerErrorCode int = 500

/*
ChangePasswordInternalServerError Internal error

swagger:response changePasswordInternalServerError
*/
type ChangePasswordInternalServerError struct {
}

// NewChangePasswordInternalServerError creates ChangePasswordInternalServerError with default headers values
func NewChangePasswordInternalServerError() *ChangePasswordInternalServerError {

	return &ChangePasswordInternalServerError{}
}

// WriteResponse to the client
func (o *ChangePasswordInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
