// Code generated by go-swagger; DO NOT EDIT.

package clients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"lim/internal/lim-handler/models"
)

// GetTrainingsByClientOKCode is the HTTP code returned for type GetTrainingsByClientOK
const GetTrainingsByClientOKCode int = 200

/*
GetTrainingsByClientOK Success

swagger:response getTrainingsByClientOK
*/
type GetTrainingsByClientOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Training `json:"body,omitempty"`
}

// NewGetTrainingsByClientOK creates GetTrainingsByClientOK with default headers values
func NewGetTrainingsByClientOK() *GetTrainingsByClientOK {

	return &GetTrainingsByClientOK{}
}

// WithPayload adds the payload to the get trainings by client o k response
func (o *GetTrainingsByClientOK) WithPayload(payload []*models.Training) *GetTrainingsByClientOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get trainings by client o k response
func (o *GetTrainingsByClientOK) SetPayload(payload []*models.Training) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTrainingsByClientOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Training, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetTrainingsByClientUnauthorizedCode is the HTTP code returned for type GetTrainingsByClientUnauthorized
const GetTrainingsByClientUnauthorizedCode int = 401

/*
GetTrainingsByClientUnauthorized Authorization error

swagger:response getTrainingsByClientUnauthorized
*/
type GetTrainingsByClientUnauthorized struct {
}

// NewGetTrainingsByClientUnauthorized creates GetTrainingsByClientUnauthorized with default headers values
func NewGetTrainingsByClientUnauthorized() *GetTrainingsByClientUnauthorized {

	return &GetTrainingsByClientUnauthorized{}
}

// WriteResponse to the client
func (o *GetTrainingsByClientUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetTrainingsByClientForbiddenCode is the HTTP code returned for type GetTrainingsByClientForbidden
const GetTrainingsByClientForbiddenCode int = 403

/*
GetTrainingsByClientForbidden No rights

swagger:response getTrainingsByClientForbidden
*/
type GetTrainingsByClientForbidden struct {
}

// NewGetTrainingsByClientForbidden creates GetTrainingsByClientForbidden with default headers values
func NewGetTrainingsByClientForbidden() *GetTrainingsByClientForbidden {

	return &GetTrainingsByClientForbidden{}
}

// WriteResponse to the client
func (o *GetTrainingsByClientForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetTrainingsByClientInternalServerErrorCode is the HTTP code returned for type GetTrainingsByClientInternalServerError
const GetTrainingsByClientInternalServerErrorCode int = 500

/*
GetTrainingsByClientInternalServerError Internal error

swagger:response getTrainingsByClientInternalServerError
*/
type GetTrainingsByClientInternalServerError struct {
}

// NewGetTrainingsByClientInternalServerError creates GetTrainingsByClientInternalServerError with default headers values
func NewGetTrainingsByClientInternalServerError() *GetTrainingsByClientInternalServerError {

	return &GetTrainingsByClientInternalServerError{}
}

// WriteResponse to the client
func (o *GetTrainingsByClientInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
