// Code generated by go-swagger; DO NOT EDIT.

package trainings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateTrainingCreatedCode is the HTTP code returned for type CreateTrainingCreated
const CreateTrainingCreatedCode int = 201

/*
CreateTrainingCreated Training successfully created

swagger:response createTrainingCreated
*/
type CreateTrainingCreated struct {
}

// NewCreateTrainingCreated creates CreateTrainingCreated with default headers values
func NewCreateTrainingCreated() *CreateTrainingCreated {

	return &CreateTrainingCreated{}
}

// WriteResponse to the client
func (o *CreateTrainingCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// CreateTrainingUnauthorizedCode is the HTTP code returned for type CreateTrainingUnauthorized
const CreateTrainingUnauthorizedCode int = 401

/*
CreateTrainingUnauthorized Authorization error

swagger:response createTrainingUnauthorized
*/
type CreateTrainingUnauthorized struct {
}

// NewCreateTrainingUnauthorized creates CreateTrainingUnauthorized with default headers values
func NewCreateTrainingUnauthorized() *CreateTrainingUnauthorized {

	return &CreateTrainingUnauthorized{}
}

// WriteResponse to the client
func (o *CreateTrainingUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// CreateTrainingForbiddenCode is the HTTP code returned for type CreateTrainingForbidden
const CreateTrainingForbiddenCode int = 403

/*
CreateTrainingForbidden No rights

swagger:response createTrainingForbidden
*/
type CreateTrainingForbidden struct {
}

// NewCreateTrainingForbidden creates CreateTrainingForbidden with default headers values
func NewCreateTrainingForbidden() *CreateTrainingForbidden {

	return &CreateTrainingForbidden{}
}

// WriteResponse to the client
func (o *CreateTrainingForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// CreateTrainingNotFoundCode is the HTTP code returned for type CreateTrainingNotFound
const CreateTrainingNotFoundCode int = 404

/*
CreateTrainingNotFound Not found

swagger:response createTrainingNotFound
*/
type CreateTrainingNotFound struct {
}

// NewCreateTrainingNotFound creates CreateTrainingNotFound with default headers values
func NewCreateTrainingNotFound() *CreateTrainingNotFound {

	return &CreateTrainingNotFound{}
}

// WriteResponse to the client
func (o *CreateTrainingNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// CreateTrainingConflictCode is the HTTP code returned for type CreateTrainingConflict
const CreateTrainingConflictCode int = 409

/*
CreateTrainingConflict Conflict error

swagger:response createTrainingConflict
*/
type CreateTrainingConflict struct {
}

// NewCreateTrainingConflict creates CreateTrainingConflict with default headers values
func NewCreateTrainingConflict() *CreateTrainingConflict {

	return &CreateTrainingConflict{}
}

// WriteResponse to the client
func (o *CreateTrainingConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// CreateTrainingUnprocessableEntityCode is the HTTP code returned for type CreateTrainingUnprocessableEntity
const CreateTrainingUnprocessableEntityCode int = 422

/*
CreateTrainingUnprocessableEntity Invalid params

swagger:response createTrainingUnprocessableEntity
*/
type CreateTrainingUnprocessableEntity struct {
}

// NewCreateTrainingUnprocessableEntity creates CreateTrainingUnprocessableEntity with default headers values
func NewCreateTrainingUnprocessableEntity() *CreateTrainingUnprocessableEntity {

	return &CreateTrainingUnprocessableEntity{}
}

// WriteResponse to the client
func (o *CreateTrainingUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}

// CreateTrainingInternalServerErrorCode is the HTTP code returned for type CreateTrainingInternalServerError
const CreateTrainingInternalServerErrorCode int = 500

/*
CreateTrainingInternalServerError Internal error

swagger:response createTrainingInternalServerError
*/
type CreateTrainingInternalServerError struct {
}

// NewCreateTrainingInternalServerError creates CreateTrainingInternalServerError with default headers values
func NewCreateTrainingInternalServerError() *CreateTrainingInternalServerError {

	return &CreateTrainingInternalServerError{}
}

// WriteResponse to the client
func (o *CreateTrainingInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
