// Code generated by go-swagger; DO NOT EDIT.

package trainings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateTrainingHandlerFunc turns a function with the right signature into a create training handler
type CreateTrainingHandlerFunc func(CreateTrainingParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateTrainingHandlerFunc) Handle(params CreateTrainingParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateTrainingHandler interface for that can handle valid create training params
type CreateTrainingHandler interface {
	Handle(CreateTrainingParams, interface{}) middleware.Responder
}

// NewCreateTraining creates a new http.Handler for the create training operation
func NewCreateTraining(ctx *middleware.Context, handler CreateTrainingHandler) *CreateTraining {
	return &CreateTraining{Context: ctx, Handler: handler}
}

/*
	CreateTraining swagger:route POST /trainings trainings createTraining

Create training
*/
type CreateTraining struct {
	Context *middleware.Context
	Handler CreateTrainingHandler
}

func (o *CreateTraining) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateTrainingParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
