// Code generated by go-swagger; DO NOT EDIT.

package trainings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteTrainingOKCode is the HTTP code returned for type DeleteTrainingOK
const DeleteTrainingOKCode int = 200

/*
DeleteTrainingOK Training successfully deleted

swagger:response deleteTrainingOK
*/
type DeleteTrainingOK struct {
}

// NewDeleteTrainingOK creates DeleteTrainingOK with default headers values
func NewDeleteTrainingOK() *DeleteTrainingOK {

	return &DeleteTrainingOK{}
}

// WriteResponse to the client
func (o *DeleteTrainingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteTrainingUnauthorizedCode is the HTTP code returned for type DeleteTrainingUnauthorized
const DeleteTrainingUnauthorizedCode int = 401

/*
DeleteTrainingUnauthorized Authorization error

swagger:response deleteTrainingUnauthorized
*/
type DeleteTrainingUnauthorized struct {
}

// NewDeleteTrainingUnauthorized creates DeleteTrainingUnauthorized with default headers values
func NewDeleteTrainingUnauthorized() *DeleteTrainingUnauthorized {

	return &DeleteTrainingUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteTrainingUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DeleteTrainingForbiddenCode is the HTTP code returned for type DeleteTrainingForbidden
const DeleteTrainingForbiddenCode int = 403

/*
DeleteTrainingForbidden No rights

swagger:response deleteTrainingForbidden
*/
type DeleteTrainingForbidden struct {
}

// NewDeleteTrainingForbidden creates DeleteTrainingForbidden with default headers values
func NewDeleteTrainingForbidden() *DeleteTrainingForbidden {

	return &DeleteTrainingForbidden{}
}

// WriteResponse to the client
func (o *DeleteTrainingForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// DeleteTrainingNotFoundCode is the HTTP code returned for type DeleteTrainingNotFound
const DeleteTrainingNotFoundCode int = 404

/*
DeleteTrainingNotFound Not found

swagger:response deleteTrainingNotFound
*/
type DeleteTrainingNotFound struct {
}

// NewDeleteTrainingNotFound creates DeleteTrainingNotFound with default headers values
func NewDeleteTrainingNotFound() *DeleteTrainingNotFound {

	return &DeleteTrainingNotFound{}
}

// WriteResponse to the client
func (o *DeleteTrainingNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteTrainingInternalServerErrorCode is the HTTP code returned for type DeleteTrainingInternalServerError
const DeleteTrainingInternalServerErrorCode int = 500

/*
DeleteTrainingInternalServerError Internal error

swagger:response deleteTrainingInternalServerError
*/
type DeleteTrainingInternalServerError struct {
}

// NewDeleteTrainingInternalServerError creates DeleteTrainingInternalServerError with default headers values
func NewDeleteTrainingInternalServerError() *DeleteTrainingInternalServerError {

	return &DeleteTrainingInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteTrainingInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
