// Code generated by go-swagger; DO NOT EDIT.

package trainings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTrainingsByClientHandlerFunc turns a function with the right signature into a get trainings by client handler
type GetTrainingsByClientHandlerFunc func(GetTrainingsByClientParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTrainingsByClientHandlerFunc) Handle(params GetTrainingsByClientParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetTrainingsByClientHandler interface for that can handle valid get trainings by client params
type GetTrainingsByClientHandler interface {
	Handle(GetTrainingsByClientParams, interface{}) middleware.Responder
}

// NewGetTrainingsByClient creates a new http.Handler for the get trainings by client operation
func NewGetTrainingsByClient(ctx *middleware.Context, handler GetTrainingsByClientHandler) *GetTrainingsByClient {
	return &GetTrainingsByClient{Context: ctx, Handler: handler}
}

/*
	GetTrainingsByClient swagger:route GET /clients/trainings trainings getTrainingsByClient

Get trainings by client
*/
type GetTrainingsByClient struct {
	Context *middleware.Context
	Handler GetTrainingsByClientHandler
}

func (o *GetTrainingsByClient) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTrainingsByClientParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
