// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"lim/internal/lim-handler/restapi/operations/assignments"
	"lim/internal/lim-handler/restapi/operations/auth"
	"lim/internal/lim-handler/restapi/operations/clients"
	"lim/internal/lim-handler/restapi/operations/coaches"
	"lim/internal/lim-handler/restapi/operations/halls"
	"lim/internal/lim-handler/restapi/operations/schedule"
	"lim/internal/lim-handler/restapi/operations/trainings"
)

// NewSwaggerLIMAPI creates a new SwaggerLIM instance
func NewSwaggerLIMAPI(spec *loads.Document) *SwaggerLIMAPI {
	return &SwaggerLIMAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		AssignmentsCreateAssignmentHandler: assignments.CreateAssignmentHandlerFunc(func(params assignments.CreateAssignmentParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation assignments.CreateAssignment has not yet been implemented")
		}),
		AssignmentsDeleteAssignmentHandler: assignments.DeleteAssignmentHandlerFunc(func(params assignments.DeleteAssignmentParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation assignments.DeleteAssignment has not yet been implemented")
		}),
		ClientsChangePasswordHandler: clients.ChangePasswordHandlerFunc(func(params clients.ChangePasswordParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation clients.ChangePassword has not yet been implemented")
		}),
		CoachesCreateCoachHandler: coaches.CreateCoachHandlerFunc(func(params coaches.CreateCoachParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation coaches.CreateCoach has not yet been implemented")
		}),
		HallsCreateHallHandler: halls.CreateHallHandlerFunc(func(params halls.CreateHallParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation halls.CreateHall has not yet been implemented")
		}),
		TrainingsCreateTrainingHandler: trainings.CreateTrainingHandlerFunc(func(params trainings.CreateTrainingParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation trainings.CreateTraining has not yet been implemented")
		}),
		TrainingsDeleteTrainingHandler: trainings.DeleteTrainingHandlerFunc(func(params trainings.DeleteTrainingParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation trainings.DeleteTraining has not yet been implemented")
		}),
		CoachesGetCoachesHandler: coaches.GetCoachesHandlerFunc(func(params coaches.GetCoachesParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation coaches.GetCoaches has not yet been implemented")
		}),
		HallsGetHallsHandler: halls.GetHallsHandlerFunc(func(params halls.GetHallsParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation halls.GetHalls has not yet been implemented")
		}),
		ScheduleGetScheduleHandler: schedule.GetScheduleHandlerFunc(func(params schedule.GetScheduleParams) middleware.Responder {
			return middleware.NotImplemented("operation schedule.GetSchedule has not yet been implemented")
		}),
		ClientsGetTrainingsByClientHandler: clients.GetTrainingsByClientHandlerFunc(func(params clients.GetTrainingsByClientParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation clients.GetTrainingsByClient has not yet been implemented")
		}),
		AuthLoginHandler: auth.LoginHandlerFunc(func(params auth.LoginParams) middleware.Responder {
			return middleware.NotImplemented("operation auth.Login has not yet been implemented")
		}),
		AuthSignupHandler: auth.SignupHandlerFunc(func(params auth.SignupParams) middleware.Responder {
			return middleware.NotImplemented("operation auth.Signup has not yet been implemented")
		}),

		// Applies when the "token" header is set
		JWTAuthAuth: func(token string) (interface{}, error) {
			return nil, errors.NotImplemented("api key auth (JWTAuth) token from header param [token] has not yet been implemented")
		},
		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*SwaggerLIMAPI the swagger l i m API */
type SwaggerLIMAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// JWTAuthAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key token provided in the header
	JWTAuthAuth func(string) (interface{}, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// AssignmentsCreateAssignmentHandler sets the operation handler for the create assignment operation
	AssignmentsCreateAssignmentHandler assignments.CreateAssignmentHandler
	// AssignmentsDeleteAssignmentHandler sets the operation handler for the delete assignment operation
	AssignmentsDeleteAssignmentHandler assignments.DeleteAssignmentHandler
	// ClientsChangePasswordHandler sets the operation handler for the change password operation
	ClientsChangePasswordHandler clients.ChangePasswordHandler
	// CoachesCreateCoachHandler sets the operation handler for the create coach operation
	CoachesCreateCoachHandler coaches.CreateCoachHandler
	// HallsCreateHallHandler sets the operation handler for the create hall operation
	HallsCreateHallHandler halls.CreateHallHandler
	// TrainingsCreateTrainingHandler sets the operation handler for the create training operation
	TrainingsCreateTrainingHandler trainings.CreateTrainingHandler
	// TrainingsDeleteTrainingHandler sets the operation handler for the delete training operation
	TrainingsDeleteTrainingHandler trainings.DeleteTrainingHandler
	// CoachesGetCoachesHandler sets the operation handler for the get coaches operation
	CoachesGetCoachesHandler coaches.GetCoachesHandler
	// HallsGetHallsHandler sets the operation handler for the get halls operation
	HallsGetHallsHandler halls.GetHallsHandler
	// ScheduleGetScheduleHandler sets the operation handler for the get schedule operation
	ScheduleGetScheduleHandler schedule.GetScheduleHandler
	// ClientsGetTrainingsByClientHandler sets the operation handler for the get trainings by client operation
	ClientsGetTrainingsByClientHandler clients.GetTrainingsByClientHandler
	// AuthLoginHandler sets the operation handler for the login operation
	AuthLoginHandler auth.LoginHandler
	// AuthSignupHandler sets the operation handler for the signup operation
	AuthSignupHandler auth.SignupHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *SwaggerLIMAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *SwaggerLIMAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *SwaggerLIMAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *SwaggerLIMAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *SwaggerLIMAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *SwaggerLIMAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *SwaggerLIMAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *SwaggerLIMAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *SwaggerLIMAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the SwaggerLIMAPI
func (o *SwaggerLIMAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.JWTAuthAuth == nil {
		unregistered = append(unregistered, "TokenAuth")
	}

	if o.AssignmentsCreateAssignmentHandler == nil {
		unregistered = append(unregistered, "assignments.CreateAssignmentHandler")
	}
	if o.AssignmentsDeleteAssignmentHandler == nil {
		unregistered = append(unregistered, "assignments.DeleteAssignmentHandler")
	}
	if o.ClientsChangePasswordHandler == nil {
		unregistered = append(unregistered, "clients.ChangePasswordHandler")
	}
	if o.CoachesCreateCoachHandler == nil {
		unregistered = append(unregistered, "coaches.CreateCoachHandler")
	}
	if o.HallsCreateHallHandler == nil {
		unregistered = append(unregistered, "halls.CreateHallHandler")
	}
	if o.TrainingsCreateTrainingHandler == nil {
		unregistered = append(unregistered, "trainings.CreateTrainingHandler")
	}
	if o.TrainingsDeleteTrainingHandler == nil {
		unregistered = append(unregistered, "trainings.DeleteTrainingHandler")
	}
	if o.CoachesGetCoachesHandler == nil {
		unregistered = append(unregistered, "coaches.GetCoachesHandler")
	}
	if o.HallsGetHallsHandler == nil {
		unregistered = append(unregistered, "halls.GetHallsHandler")
	}
	if o.ScheduleGetScheduleHandler == nil {
		unregistered = append(unregistered, "schedule.GetScheduleHandler")
	}
	if o.ClientsGetTrainingsByClientHandler == nil {
		unregistered = append(unregistered, "clients.GetTrainingsByClientHandler")
	}
	if o.AuthLoginHandler == nil {
		unregistered = append(unregistered, "auth.LoginHandler")
	}
	if o.AuthSignupHandler == nil {
		unregistered = append(unregistered, "auth.SignupHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *SwaggerLIMAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *SwaggerLIMAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {
		case "JWTAuth":
			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, o.JWTAuthAuth)

		}
	}
	return result
}

// Authorizer returns the registered authorizer
func (o *SwaggerLIMAPI) Authorizer() runtime.Authorizer {
	return o.APIAuthorizer
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *SwaggerLIMAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *SwaggerLIMAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *SwaggerLIMAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the swagger l i m API
func (o *SwaggerLIMAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *SwaggerLIMAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/assignments"] = assignments.NewCreateAssignment(o.context, o.AssignmentsCreateAssignmentHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/assignments"] = assignments.NewDeleteAssignment(o.context, o.AssignmentsDeleteAssignmentHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/clients"] = clients.NewChangePassword(o.context, o.ClientsChangePasswordHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/coaches"] = coaches.NewCreateCoach(o.context, o.CoachesCreateCoachHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/halls"] = halls.NewCreateHall(o.context, o.HallsCreateHallHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/trainings"] = trainings.NewCreateTraining(o.context, o.TrainingsCreateTrainingHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/trainings"] = trainings.NewDeleteTraining(o.context, o.TrainingsDeleteTrainingHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/coaches"] = coaches.NewGetCoaches(o.context, o.CoachesGetCoachesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/halls/{date}"] = halls.NewGetHalls(o.context, o.HallsGetHallsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/schedule"] = schedule.NewGetSchedule(o.context, o.ScheduleGetScheduleHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/clients/trainings"] = clients.NewGetTrainingsByClient(o.context, o.ClientsGetTrainingsByClientHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/login"] = auth.NewLogin(o.context, o.AuthLoginHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/signup"] = auth.NewSignup(o.context, o.AuthSignupHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *SwaggerLIMAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *SwaggerLIMAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *SwaggerLIMAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *SwaggerLIMAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *SwaggerLIMAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[um][path] = builder(h)
	}
}
