// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Lost In Motion",
    "version": "1.0.0"
  },
  "host": "0.0.0.0:8081",
  "basePath": "/api/v1",
  "paths": {
    "/assignments": {
      "post": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "assignments"
        ],
        "summary": "Create assignment",
        "operationId": "CreateAssignment",
        "parameters": [
          {
            "description": "Идентификатор тренировки",
            "name": "training_id",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/TrainingID"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Assignment successfully created"
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "404": {
            "description": "Not found"
          },
          "409": {
            "description": "Validation error"
          },
          "422": {
            "description": "Invalid params"
          },
          "500": {
            "description": "Internal error"
          }
        }
      },
      "delete": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "assignments"
        ],
        "summary": "Delete assignment",
        "operationId": "DeleteAssignment",
        "parameters": [
          {
            "description": "Идентификатор тренировки",
            "name": "training_id",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/TrainingID"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Assignment successfully deleted"
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "404": {
            "description": "Not found"
          },
          "422": {
            "description": "Invalid params"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/clients": {
      "patch": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "clients"
        ],
        "summary": "Change password",
        "operationId": "changePassword",
        "parameters": [
          {
            "description": "Новый пароль",
            "name": "new_password",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ClientChangePassword"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "404": {
            "description": "No such client"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/clients/trainings": {
      "get": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "clients"
        ],
        "summary": "Get trainings by client",
        "operationId": "getTrainingsByClient",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Training"
              }
            }
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/coaches": {
      "get": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "coaches"
        ],
        "summary": "Get coaches",
        "operationId": "getCoaches",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Coach"
              }
            }
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "500": {
            "description": "Internal error"
          }
        }
      },
      "post": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "coaches"
        ],
        "summary": "Create coach",
        "operationId": "createCoach",
        "parameters": [
          {
            "description": "Информация о тренере для создания",
            "name": "coach_info",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CoachInfo"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Coach successfully created"
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "409": {
            "description": "Coach alredy exists"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/halls": {
      "post": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "halls"
        ],
        "summary": "Create hall",
        "operationId": "createHall",
        "parameters": [
          {
            "description": "Информация о зале для создания",
            "name": "hall_info",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/HallInfo"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Hall successfully created"
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "409": {
            "description": "Hall alredy exists"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/halls/{date}": {
      "get": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "halls"
        ],
        "summary": "Get halls by date",
        "operationId": "getHalls",
        "parameters": [
          {
            "type": "string",
            "format": "date",
            "description": "Дата",
            "name": "date",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "hall": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/Hall"
                    }
                  },
                  "timestamp": {
                    "type": "string",
                    "format": "time"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "422": {
            "description": "Invalid params"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": [
          "auth"
        ],
        "summary": "Login",
        "operationId": "login",
        "parameters": [
          {
            "description": "Информация о клиенте для входа",
            "name": "client_login_info",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ClientLoginInfo"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Client successfully logged in",
            "schema": {
              "$ref": "#/definitions/Token"
            }
          },
          "401": {
            "description": "Authorization error"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/schedule": {
      "get": {
        "tags": [
          "schedule"
        ],
        "summary": "Get training schedule",
        "operationId": "getSchedule",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Training"
              }
            }
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/signup": {
      "post": {
        "tags": [
          "auth"
        ],
        "summary": "Create client",
        "operationId": "signup",
        "parameters": [
          {
            "description": "Информация о клиенте для регистрации",
            "name": "client_info",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ClientInfo"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Client successfully created"
          },
          "409": {
            "description": "Client alredy exists"
          },
          "422": {
            "description": "Invalid params"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/trainings": {
      "post": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "trainings"
        ],
        "summary": "Create training",
        "operationId": "createTraining",
        "parameters": [
          {
            "description": "Информация о тренировке для создания",
            "name": "training_info",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/TrainingInfo"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Training successfully created"
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "404": {
            "description": "Not found"
          },
          "409": {
            "description": "Conflict error"
          },
          "422": {
            "description": "Invalid params"
          },
          "500": {
            "description": "Internal error"
          }
        }
      },
      "delete": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "trainings"
        ],
        "summary": "Delete training",
        "operationId": "deleteTraining",
        "parameters": [
          {
            "description": "Идентификатор тренировки",
            "name": "training_id",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/TrainingID"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Training successfully deleted"
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "404": {
            "description": "Not found"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    }
  },
  "definitions": {
    "Client": {
      "type": "object",
      "required": [
        "client_id",
        "name",
        "telephone",
        "email",
        "password"
      ],
      "properties": {
        "client_id": {
          "type": "integer",
          "format": "uint64"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "name": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "telephone": {
          "type": "string"
        }
      }
    },
    "ClientChangePassword": {
      "type": "object",
      "required": [
        "password"
      ],
      "properties": {
        "password": {
          "type": "string"
        }
      }
    },
    "ClientInfo": {
      "type": "object",
      "required": [
        "name",
        "telephone",
        "email",
        "password"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email"
        },
        "name": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "telephone": {
          "type": "string"
        }
      }
    },
    "ClientLoginInfo": {
      "type": "object",
      "required": [
        "telephone",
        "password"
      ],
      "properties": {
        "password": {
          "type": "string"
        },
        "telephone": {
          "type": "string"
        }
      }
    },
    "Coach": {
      "type": "object",
      "required": [
        "coach_id",
        "name"
      ],
      "properties": {
        "coach_id": {
          "type": "integer",
          "format": "uint64"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "CoachInfo": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string"
        }
      }
    },
    "Hall": {
      "type": "object",
      "required": [
        "hall_id",
        "number"
      ],
      "properties": {
        "hall_id": {
          "type": "integer",
          "format": "uint64"
        },
        "number": {
          "type": "integer",
          "format": "uint64"
        }
      }
    },
    "HallInfo": {
      "type": "object",
      "required": [
        "number"
      ],
      "properties": {
        "number": {
          "type": "integer",
          "format": "uint64"
        }
      }
    },
    "Token": {
      "type": "object",
      "properties": {
        "access_key": {
          "description": "JWT access key",
          "type": "string"
        }
      }
    },
    "Training": {
      "type": "object",
      "required": [
        "training_id",
        "coach_name",
        "hall_number",
        "name",
        "date_time",
        "places_num"
      ],
      "properties": {
        "coach_name": {
          "type": "string"
        },
        "date_time": {
          "type": "string",
          "format": "date-time"
        },
        "hall_number": {
          "type": "integer",
          "format": "uint64"
        },
        "name": {
          "type": "string"
        },
        "places_num": {
          "type": "integer",
          "format": "uint64"
        },
        "training_id": {
          "type": "integer",
          "format": "uint64"
        }
      }
    },
    "TrainingID": {
      "type": "object",
      "required": [
        "training_id"
      ],
      "properties": {
        "training_id": {
          "type": "integer",
          "format": "uint64"
        }
      }
    },
    "TrainingInfo": {
      "type": "object",
      "required": [
        "coach_name",
        "hall_number",
        "name",
        "date_time",
        "places_num"
      ],
      "properties": {
        "coach_name": {
          "type": "string"
        },
        "date_time": {
          "type": "string",
          "format": "date-time"
        },
        "hall_number": {
          "type": "integer",
          "format": "uint64"
        },
        "name": {
          "type": "string"
        },
        "places_num": {
          "type": "integer",
          "format": "uint64"
        }
      }
    }
  },
  "responses": {
    "UnauthorizedError": {
      "description": "Authentication error",
      "headers": {
        "WWW_Authenticate": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "JWTAuth": {
      "type": "apiKey",
      "name": "token",
      "in": "header"
    }
  },
  "tags": [
    {
      "name": "auth"
    },
    {
      "name": "schedule"
    },
    {
      "name": "clients"
    },
    {
      "name": "coaches"
    },
    {
      "name": "halls"
    },
    {
      "name": "trainings"
    },
    {
      "name": "assignments"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Lost In Motion",
    "version": "1.0.0"
  },
  "host": "0.0.0.0:8081",
  "basePath": "/api/v1",
  "paths": {
    "/assignments": {
      "post": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "assignments"
        ],
        "summary": "Create assignment",
        "operationId": "CreateAssignment",
        "parameters": [
          {
            "description": "Идентификатор тренировки",
            "name": "training_id",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/TrainingID"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Assignment successfully created"
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "404": {
            "description": "Not found"
          },
          "409": {
            "description": "Validation error"
          },
          "422": {
            "description": "Invalid params"
          },
          "500": {
            "description": "Internal error"
          }
        }
      },
      "delete": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "assignments"
        ],
        "summary": "Delete assignment",
        "operationId": "DeleteAssignment",
        "parameters": [
          {
            "description": "Идентификатор тренировки",
            "name": "training_id",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/TrainingID"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Assignment successfully deleted"
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "404": {
            "description": "Not found"
          },
          "422": {
            "description": "Invalid params"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/clients": {
      "patch": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "clients"
        ],
        "summary": "Change password",
        "operationId": "changePassword",
        "parameters": [
          {
            "description": "Новый пароль",
            "name": "new_password",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ClientChangePassword"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "404": {
            "description": "No such client"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/clients/trainings": {
      "get": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "clients"
        ],
        "summary": "Get trainings by client",
        "operationId": "getTrainingsByClient",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Training"
              }
            }
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/coaches": {
      "get": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "coaches"
        ],
        "summary": "Get coaches",
        "operationId": "getCoaches",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Coach"
              }
            }
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "500": {
            "description": "Internal error"
          }
        }
      },
      "post": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "coaches"
        ],
        "summary": "Create coach",
        "operationId": "createCoach",
        "parameters": [
          {
            "description": "Информация о тренере для создания",
            "name": "coach_info",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CoachInfo"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Coach successfully created"
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "409": {
            "description": "Coach alredy exists"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/halls": {
      "post": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "halls"
        ],
        "summary": "Create hall",
        "operationId": "createHall",
        "parameters": [
          {
            "description": "Информация о зале для создания",
            "name": "hall_info",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/HallInfo"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Hall successfully created"
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "409": {
            "description": "Hall alredy exists"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/halls/{date}": {
      "get": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "halls"
        ],
        "summary": "Get halls by date",
        "operationId": "getHalls",
        "parameters": [
          {
            "type": "string",
            "format": "date",
            "description": "Дата",
            "name": "date",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/GetHallsOKBodyItems0"
              }
            }
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "422": {
            "description": "Invalid params"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": [
          "auth"
        ],
        "summary": "Login",
        "operationId": "login",
        "parameters": [
          {
            "description": "Информация о клиенте для входа",
            "name": "client_login_info",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ClientLoginInfo"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Client successfully logged in",
            "schema": {
              "$ref": "#/definitions/Token"
            }
          },
          "401": {
            "description": "Authorization error"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/schedule": {
      "get": {
        "tags": [
          "schedule"
        ],
        "summary": "Get training schedule",
        "operationId": "getSchedule",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Training"
              }
            }
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/signup": {
      "post": {
        "tags": [
          "auth"
        ],
        "summary": "Create client",
        "operationId": "signup",
        "parameters": [
          {
            "description": "Информация о клиенте для регистрации",
            "name": "client_info",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ClientInfo"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Client successfully created"
          },
          "409": {
            "description": "Client alredy exists"
          },
          "422": {
            "description": "Invalid params"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/trainings": {
      "post": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "trainings"
        ],
        "summary": "Create training",
        "operationId": "createTraining",
        "parameters": [
          {
            "description": "Информация о тренировке для создания",
            "name": "training_info",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/TrainingInfo"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Training successfully created"
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "404": {
            "description": "Not found"
          },
          "409": {
            "description": "Conflict error"
          },
          "422": {
            "description": "Invalid params"
          },
          "500": {
            "description": "Internal error"
          }
        }
      },
      "delete": {
        "security": [
          {
            "JWTAuth": []
          }
        ],
        "tags": [
          "trainings"
        ],
        "summary": "Delete training",
        "operationId": "deleteTraining",
        "parameters": [
          {
            "description": "Идентификатор тренировки",
            "name": "training_id",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/TrainingID"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Training successfully deleted"
          },
          "401": {
            "description": "Authorization error"
          },
          "403": {
            "description": "No rights"
          },
          "404": {
            "description": "Not found"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    }
  },
  "definitions": {
    "Client": {
      "type": "object",
      "required": [
        "client_id",
        "name",
        "telephone",
        "email",
        "password"
      ],
      "properties": {
        "client_id": {
          "type": "integer",
          "format": "uint64"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "name": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "telephone": {
          "type": "string"
        }
      }
    },
    "ClientChangePassword": {
      "type": "object",
      "required": [
        "password"
      ],
      "properties": {
        "password": {
          "type": "string"
        }
      }
    },
    "ClientInfo": {
      "type": "object",
      "required": [
        "name",
        "telephone",
        "email",
        "password"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email"
        },
        "name": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "telephone": {
          "type": "string"
        }
      }
    },
    "ClientLoginInfo": {
      "type": "object",
      "required": [
        "telephone",
        "password"
      ],
      "properties": {
        "password": {
          "type": "string"
        },
        "telephone": {
          "type": "string"
        }
      }
    },
    "Coach": {
      "type": "object",
      "required": [
        "coach_id",
        "name"
      ],
      "properties": {
        "coach_id": {
          "type": "integer",
          "format": "uint64"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "CoachInfo": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string"
        }
      }
    },
    "GetHallsOKBodyItems0": {
      "type": "object",
      "properties": {
        "hall": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Hall"
          }
        },
        "timestamp": {
          "type": "string",
          "format": "time"
        }
      }
    },
    "Hall": {
      "type": "object",
      "required": [
        "hall_id",
        "number"
      ],
      "properties": {
        "hall_id": {
          "type": "integer",
          "format": "uint64"
        },
        "number": {
          "type": "integer",
          "format": "uint64"
        }
      }
    },
    "HallInfo": {
      "type": "object",
      "required": [
        "number"
      ],
      "properties": {
        "number": {
          "type": "integer",
          "format": "uint64"
        }
      }
    },
    "Token": {
      "type": "object",
      "properties": {
        "access_key": {
          "description": "JWT access key",
          "type": "string"
        }
      }
    },
    "Training": {
      "type": "object",
      "required": [
        "training_id",
        "coach_name",
        "hall_number",
        "name",
        "date_time",
        "places_num"
      ],
      "properties": {
        "coach_name": {
          "type": "string"
        },
        "date_time": {
          "type": "string",
          "format": "date-time"
        },
        "hall_number": {
          "type": "integer",
          "format": "uint64"
        },
        "name": {
          "type": "string"
        },
        "places_num": {
          "type": "integer",
          "format": "uint64"
        },
        "training_id": {
          "type": "integer",
          "format": "uint64"
        }
      }
    },
    "TrainingID": {
      "type": "object",
      "required": [
        "training_id"
      ],
      "properties": {
        "training_id": {
          "type": "integer",
          "format": "uint64"
        }
      }
    },
    "TrainingInfo": {
      "type": "object",
      "required": [
        "coach_name",
        "hall_number",
        "name",
        "date_time",
        "places_num"
      ],
      "properties": {
        "coach_name": {
          "type": "string"
        },
        "date_time": {
          "type": "string",
          "format": "date-time"
        },
        "hall_number": {
          "type": "integer",
          "format": "uint64"
        },
        "name": {
          "type": "string"
        },
        "places_num": {
          "type": "integer",
          "format": "uint64"
        }
      }
    }
  },
  "responses": {
    "UnauthorizedError": {
      "description": "Authentication error",
      "headers": {
        "WWW_Authenticate": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "JWTAuth": {
      "type": "apiKey",
      "name": "token",
      "in": "header"
    }
  },
  "tags": [
    {
      "name": "auth"
    },
    {
      "name": "schedule"
    },
    {
      "name": "clients"
    },
    {
      "name": "coaches"
    },
    {
      "name": "halls"
    },
    {
      "name": "trainings"
    },
    {
      "name": "assignments"
    }
  ]
}`))
}
