// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Coach coach
//
// swagger:model Coach
type Coach struct {

	// coach id
	// Required: true
	CoachID *uint64 `json:"coach_id"`

	// name
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this coach
func (m *Coach) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCoachID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Coach) validateCoachID(formats strfmt.Registry) error {

	if err := validate.Required("coach_id", "body", m.CoachID); err != nil {
		return err
	}

	return nil
}

func (m *Coach) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this coach based on context it is used
func (m *Coach) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Coach) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Coach) UnmarshalBinary(b []byte) error {
	var res Coach
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
