// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Hall hall
//
// swagger:model Hall
type Hall struct {

	// hall id
	// Required: true
	HallID *uint64 `json:"hall_id"`

	// number
	// Required: true
	Number *uint64 `json:"number"`
}

// Validate validates this hall
func (m *Hall) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHallID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNumber(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Hall) validateHallID(formats strfmt.Registry) error {

	if err := validate.Required("hall_id", "body", m.HallID); err != nil {
		return err
	}

	return nil
}

func (m *Hall) validateNumber(formats strfmt.Registry) error {

	if err := validate.Required("number", "body", m.Number); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this hall based on context it is used
func (m *Hall) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Hall) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Hall) UnmarshalBinary(b []byte) error {
	var res Hall
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
