// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TrainingID training ID
//
// swagger:model TrainingID
type TrainingID struct {

	// training id
	// Required: true
	TrainingID *uint64 `json:"training_id"`
}

// Validate validates this training ID
func (m *TrainingID) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTrainingID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TrainingID) validateTrainingID(formats strfmt.Registry) error {

	if err := validate.Required("training_id", "body", m.TrainingID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this training ID based on context it is used
func (m *TrainingID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TrainingID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TrainingID) UnmarshalBinary(b []byte) error {
	var res TrainingID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
