// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TrainingInfo training info
//
// swagger:model TrainingInfo
type TrainingInfo struct {

	// coach name
	// Required: true
	CoachName *string `json:"coach_name"`

	// date time
	// Required: true
	// Format: date-time
	DateTime *strfmt.DateTime `json:"date_time"`

	// hall number
	// Required: true
	HallNumber *uint64 `json:"hall_number"`

	// name
	// Required: true
	Name *string `json:"name"`

	// places num
	// Required: true
	PlacesNum *uint64 `json:"places_num"`
}

// Validate validates this training info
func (m *TrainingInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCoachName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDateTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHallNumber(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlacesNum(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TrainingInfo) validateCoachName(formats strfmt.Registry) error {

	if err := validate.Required("coach_name", "body", m.CoachName); err != nil {
		return err
	}

	return nil
}

func (m *TrainingInfo) validateDateTime(formats strfmt.Registry) error {

	if err := validate.Required("date_time", "body", m.DateTime); err != nil {
		return err
	}

	if err := validate.FormatOf("date_time", "body", "date-time", m.DateTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *TrainingInfo) validateHallNumber(formats strfmt.Registry) error {

	if err := validate.Required("hall_number", "body", m.HallNumber); err != nil {
		return err
	}

	return nil
}

func (m *TrainingInfo) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *TrainingInfo) validatePlacesNum(formats strfmt.Registry) error {

	if err := validate.Required("places_num", "body", m.PlacesNum); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this training info based on context it is used
func (m *TrainingInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TrainingInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TrainingInfo) UnmarshalBinary(b []byte) error {
	var res TrainingInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
