// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TrainingClient training client
//
// swagger:model TrainingClient
type TrainingClient struct {

	// client id
	// Required: true
	ClientID *uint64 `json:"client_id"`

	// training id
	// Required: true
	TrainingID *uint64 `json:"training_id"`
}

// Validate validates this training client
func (m *TrainingClient) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClientID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTrainingID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TrainingClient) validateClientID(formats strfmt.Registry) error {

	if err := validate.Required("client_id", "body", m.ClientID); err != nil {
		return err
	}

	return nil
}

func (m *TrainingClient) validateTrainingID(formats strfmt.Registry) error {

	if err := validate.Required("training_id", "body", m.TrainingID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this training client based on context it is used
func (m *TrainingClient) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TrainingClient) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TrainingClient) UnmarshalBinary(b []byte) error {
	var res TrainingClient
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
